version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ignore certain platform combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/quick-branch/main.go

archives:
  - formats:
      - tar.gz
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "typo"

# Homebrew setup
homebrew_casks:
  - name: quick-branch
    repository:
      owner: rangoons
      name: homebrew-tap

    # Casks directory is the default, but explicitly setting it
    directory: Casks

    homepage: "https://github.com/rangoons/quick-branch"
    description: "Quick branch creation tool for Linear issues"
    license: "MIT"

    # The binaries to include (defaults to cask name if not specified)
    binaries:
      - quick-branch

    # Optional: if your app/binary isn't signed and notarized, you'll need this:
    # This removes macOS quarantine attribute from unsigned binaries
    custom_block: |
      postflight do
        system_command "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "#{staged_path}"],
          sudo: false
      end
