version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ignore certain platform combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/quick-branch/main.go

archives:
  - format: tar.gz
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "typo"

# Homebrew setup
brews:
  - name: quick-branch
    # Create a tap repository at github.com/rangoons/homebrew-tap
    # Or use github.com/rangoons/homebrew-quick-branch
    repository:
      owner: rangoons
      name: homebrew-tap

    directory: Formula

    homepage: "https://github.com/rangoons/quick-branch"

    description: "Quick branch creation tool for Linear issues"

    license: "MIT"

    install: |
      bin.install "quick-branch"

    test: |
      system "#{bin}/quick-branch", "--version"
